const DATABASE_NAME = '@delivers-app';

const COLLECTION_ROUTES = `${DATABASE_NAME}:routes`;
const COLLECTION_ORDERS_ROUTE = `${DATABASE_NAME}:ordersRoute`;
const COLLECTION_SUMMARY_ROUTE = `${DATABASE_NAME}:summaryRoute`;
const COLLECTION_DELIVERS = `${DATABASE_NAME}:delivers`;

export {
  COLLECTION_ROUTES,
  COLLECTION_ORDERS_ROUTE,
  COLLECTION_SUMMARY_ROUTE,
  COLLECTION_DELIVERS,
};